services:
  # Main homepage/portfolio site
  homepage:
    image: nginx:alpine
    volumes:
      - ./homepage:/usr/share/nginx/html  # Your main website files
    expose:
      - "80"
    restart: unless-stopped
  
  shapeshifters:
    image: nginx:alpine
    volumes:
      - ./shapeshifters:/usr/share/nginx/html  # Your Shapeshifters website files
    expose:
      - "80"
    restart: unless-stopped

  # Local nginx - simple HTTP setup for CooperAItion development
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf
    depends_on:
      - homepage
      - shapeshifters
      - frontend
      - backend
    restart: unless-stopped

  backend:
    build: 
      context: ./cooperAItion-backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./cooperAItion-backend:/app  # Volume mounting for development
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: 
      context: ./cooperAItion-frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    volumes:
      - ./cooperAItion-frontend/src:/app/src  # Volume mounting for development
    depends_on:
      - backend
    restart: unless-stopped
